server:
  port: 8081
# Actuator는 서버에 대한 다양한 정보를 다룬다. 보안에 주의를 더 기울여야 한다.
# 1. management port와 service port를 분리하자.
# 2. Actuator 접근 시, Security 등을 활용하여 인증과 권한 여부를 검사하자.
# 3. Actuator Default 경로를 사용하지 않고, base-path를 변경하여 운영한다.

chat:
  test-profile: ${TEST_PROFILE}

spring:
  config:
    import:
      - classpath:/database/application-mysql.yml
      - classpath:/database/application-redis.yml
      - classpath:/monitor/application-actuator.yml
      - classpath:/security/application-security.yml

profile:
  base-url: ${PROFILE_BASEURL}

kafka:
  bootstrap-server: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

chatgpt:
  api-key: ${OPENAI_SECRET_KEY}
  model: ${OPENAI_MODEL}